# _config.yml

# required, replace with your own information -----
title: Personal Website 
author: Denise J. Roth
description: > 
  PhD Candidate in Political Communication
baseurl: ""
google_site_verification: WqwhLKWThOFVhNyiX8m5Qw0yv9Gj85ywwlnMrUO8P_Y
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

